# Generated by Django 6.0 on 2025-12-08 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=100)),
                ('sellable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom product attributes from form builder')),
                ('form_schema', models.ForeignKey(blank=True, help_text='Associated form schema for custom product fields', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='forms_app.formschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sales_table', models.CharField(help_text='Reference to sales table/view', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(default=dict, help_text='Dashboard layout and widget configuration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='products.productform')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.productform')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.AddIndex(
            model_name='productform',
            index=models.Index(fields=['user', '-created_at'], name='products_pr_user_id_0809a1_idx'),
        ),
        migrations.AddIndex(
            model_name='productform',
            index=models.Index(fields=['product_type'], name='products_pr_product_7e499b_idx'),
        ),
        migrations.AddIndex(
            model_name='productform',
            index=models.Index(fields=['sellable'], name='products_pr_sellabl_b91617_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['user', '-created_at'], name='products_da_user_id_37bf06_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['product', '-sale_date'], name='products_sa_product_847aa3_idx'),
        ),
    ]
