# Generated by Django 6.0 on 2025-12-08 09:17

import django.db.models.deletion
import forms_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the form', max_length=255)),
                ('slug', models.SlugField(default=forms_app.models.generate_unique_slug, help_text='Unique URL identifier for accessing the form', max_length=8, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language_config', models.JSONField(default=dict, help_text='Primary and optional language codes')),
                ('fields_structure', models.JSONField(default=list, help_text='Array of field definitions')),
                ('relationships', models.JSONField(default=list, help_text='Defines relationships to other forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='User-submitted data matching the form schema')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('form_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_app.formschema')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='forms_app_f_submitt_aa9387_idx'), models.Index(fields=['form_schema', '-submitted_at'], name='forms_app_f_form_sc_879773_idx')],
            },
        ),
    ]
