# Generated by Django 6.0 on 2025-12-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_formfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='formschema',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
