# Generated by Django 6.0 on 2025-12-14 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display label for the field', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('textarea', 'TextArea'), ('select', 'Dropdown'), ('checkbox', 'Checkbox')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('choices', models.TextField(blank=True, help_text='For dropdown: Option1,Option2,Option3', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='UserHome.profilefield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_values', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='profilefield',
            index=models.Index(fields=['user', 'order'], name='UserHome_pr_user_id_811180_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profilefield',
            unique_together={('user', 'label')},
        ),
        migrations.AddIndex(
            model_name='profilevalue',
            index=models.Index(fields=['user'], name='UserHome_pr_user_id_75cab5_idx'),
        ),
        migrations.AddIndex(
            model_name='profilevalue',
            index=models.Index(fields=['field'], name='UserHome_pr_field_i_3e0abb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profilevalue',
            unique_together={('user', 'field')},
        ),
    ]
